name: Nuitka Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:
    runs-on: windows-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12' 
            architecture: 'x64' 
        
        - name: Install Python Requirements
          run: |
            pip install --no-cache-dir --upgrade -r requirements.txt
            pip install Nuitka imageio

        - name: Build with Nuitka
          run: |
            python -m nuitka `
              --windows-console-mode=disable `
              --standalone `
              --show-progress `
              --show-memory `
              --assume-yes-for-downloads
              --include-package=comtypes `
              --include-module=comtypes.stream `
              --windows-icon-from-ico=./app-icon.png `
              --enable-plugin=pyside6 `
              --output-dir=build `
              main.py
        
        # - name: Nuitka Build
        #   uses: Nuitka/Nuitka-Action@main
        #   with:
        #     nuitka-version: main
        #     script-name: main.py
        #     mode: standalone
        #     enable-plugins: pyside6

        - name: Rename EXE
          run: move build\main.dist\main.exe build\main.dist\live-caption-py.exe 


        - name: Upload
          uses: softprops/action-gh-release@v2
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: build/main.dist/live-caption-py.exe 